<a href="https://colab.research.google.com/github/ramani-coder/ExamCellAutomationFinal/blob/main/Assignment1(FDS).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
r = ["aman", "222", 777, 400.4]
r=tuple(r)
print(r)

('aman', '222', 777, 400.4)


In [3]:
d = {"roll no":7, "first name":"annapurna", "last name":"ramani", "Date of birth":"17/02/2003"}
print(d)

{'roll no': 7, 'first name': 'annapurna', 'last name': 'ramani', 'Date of birth': '17/02/2003'}


In [11]:
import numpy as np
np.random.seed(0)
r= np.random.rand(3,5)
print(r)

[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]]


In [10]:
import random
r= random.uniform(0,1)
print(r)
print(abs(-1234))

0.6848408462156437
1234


In [11]:
import random
r=random.randint(20,90)
print(r)

82


In [16]:
import numpy as np
r=[11, 12, 13,14, 15]
x=np.random.choice(r,3,replace=False)
print(x)
random.shuffle(r)
print(r)
print(np.random.choice(r,1))

[14 12 15]
[11, 14, 15, 12, 13]
[15]


In [6]:
file1 = open("MyFile.txt","w")
str1= "The King is Dead, Long Live The King" 
file1.write(str1)
file1.close()
file1 = open("MyFile.txt","r")
print(file1.read())
file1.close()

The King is Dead, Long Live The King


In [8]:
num = 3.4
if num > 0:
    print("Positive number")
elif num == 0:
    print("Zero")
else:
    print("Negative number")
print("\nBreak:\n")
for val in "string":
    if val == "i":
        break
    print(val)

print("The end")
print("\nContinue:\n")
for val in "string":
    if val == "i":
        continue
    print(val)

print("The end")

Positive number

Break:

s
t
r
The end

Continue:

s
t
r
n
g
The end


In [9]:
str1="The King is Dead, Long Live The King"
print(str1)
print(str1[0])
print(str1[3:6])
print(str1[3:])
x=str1.split()
print(x)

The King is Dead, Long Live The King
T
 Ki
 King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


In [10]:
arr=[1,4,5,8]
print(arr[0:1],arr[1:2])

[1] [4]


In [20]:
arr=[[1,2,3],[4,5,6]]
print(arr)
print(arr[1:])
for i in arr:
  print(i[1:])
print(len(arr))

[[1, 2, 3], [4, 5, 6]]
[[4, 5, 6]]
[2, 3]
[5, 6]
2


In [24]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
x.shape=(2,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [26]:
l1=[1,2,3]
x=np.array(l1)
print(x)

[1 2 3]


In [30]:
arr=np.array([1,2,3])
arr.fill(9)
print(arr)

[9 9 9]


In [31]:
arr=np.array([2,4,5])
print(np.sum(arr))

11


In [32]:
arr=np.array([77,74,75])
print(np.prod(arr))

427350


In [34]:
arr=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print(np.mean(arr),np.var(arr),np.amax(arr),np.amin(arr),np.argmin(arr),np.argmax(arr),np.median(arr),np.std(arr))

12.461538461538462 367.32544378698225 56 1 1 12 2.0 19.165736192147232


In [38]:
l=np.array([1, 1, 4, 5, 5, 5, 7])
print(np.unique(l))

[1 4 5 7]


In [39]:
l=np.array([1, 2, 3])
l1=np.array([0, 1, 1])
print(np.dot(l,l1))

5


In [41]:
from numpy.linalg import eig
a = np.array([[2, 2, 4], 
              [1, 3, 5],
              [2, 3, 4]])
w,v=eig(a)
print('E-value:', w)
print('E-vector', v)

E-value: [ 8.80916362  0.92620912 -0.73537273]
E-vector [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]


In [44]:
x_simple = np.array([11, 22, 11, 31])
y_simple = np.array([25, 33, 31, 28])
my_rho = np.corrcoef(x_simple, y_simple)

print(my_rho)

[[1.         0.15997968]
 [0.15997968 1.        ]]
